# REDIS (RedisProperties)
# Redis 数据索引(默认为0)
spring:
  redis:
    database: 0         # Redis 在配置的时候可以设置数据库数量,默认为16,可以理解为数据库的schema
    host: 127.0.0.1     # Redis 服务器地址
    port: 6379          # Redis 服务器连接端口
    password:           # Redis 服务器连接密码(默认为空) 
    pool:
      max-active: 8     # Redis 最大连接数(使用负值表示没有限制)
      max-wait: -1      # Redis 连接池最大阻塞等待时间(使用负值表示没有限制)
      max-idle: 8       # Redis 连接池中的最大空闲连接
      min-idle: 0       # Redis 连接池中的最小空闲连接
    timeout: 0          # Redis 连接超时时间(毫秒)